apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: magento
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Added storageClassName for dynamic provisioning
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: magento
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: magento
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 533267151748.dkr.ecr.us-east-1.amazonaws.com/magento-repo:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
            - name: MYSQL_DATABASE
              value: magento
            - name: MYSQL_USER
              value: magento
            - name: MYSQL_PASSWORD
              value: magentopass
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-pvc
  namespace: magento
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard  # Added storageClassName for dynamic provisioning
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
  namespace: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
        - name: magento
          image: 533267151748.dkr.ecr.us-east-1.amazonaws.com/magento-repo:latest
          ports:
            - containerPort: 80
          env:
            - name: MAGE_RUN_CODE
              value: "default"
            - name: MAGE_RUN_TYPE
              value: "store"
            - name: MAGENTO_DB_HOST
              value: "mysql"
            - name: MAGENTO_DB_NAME
              value: "magento"
            - name: MAGENTO_DB_USER
              value: "magento"
            - name: MAGENTO_DB_PASSWORD
              value: "magentopass"
          volumeMounts:
            - name: magento-data
              mountPath: /var/www/html
      volumes:
        - name: magento-data
          persistentVolumeClaim:
            claimName: magento-pvc
