apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-pvc
  namespace: magento
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
  namespace: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
        - name: magento
          image: 471112659821.dkr.ecr.us-east-1.amazonaws.com/magento-repo:2.4.7-apache
          ports:
            - containerPort: 80
          env:
            - name: MAGE_RUN_CODE
              value: "default"
            - name: MAGE_RUN_TYPE
              value: "store"
            - name: MAGENTO_DB_HOST
              value: "mysql"
            - name: MAGENTO_DB_NAME
              value: "magento"
            - name: MAGENTO_DB_USER
              value: "magento"
            - name: MAGENTO_DB_PASSWORD
              value: "magentopass"
          volumeMounts:
            - name: magento-data
              mountPath: /var/www/html
      volumes:
        - name: magento-data
          persistentVolumeClaim:
            claimName: magento-pvc
