apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
  namespace: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
        - name: magento
          image: 851725392626.dkr.ecr.us-east-1.amazonaws.com/magento-repo:latest
          ports:
            - containerPort: 8080
          env:
            - name: MAGENTO_MODE
              value: developer
          volumeMounts:
            - name: magento-storage
              mountPath: /bitnami/magento
      volumes:
        - name: magento-storage
          emptyDir: {}  # Replace with a PVC if needed
